const $ = (s, p=document) => p.querySelector(s);
const uid = () => Math.random().toString(36).slice(2, 9);
const deep = o => JSON.parse(JSON.stringify(o));
const state = { format:'4:5', active:0, tool:'slides', selected:null, history:[], redo:[], preview: false,
  slides: [], projectName: 'Осенние истории', dragging:null };
const templates = [
  {name:'Обложка', icon:'✦', bg:'#f3eee7', els:[{type:'shape',shape:'rect',x:0,y:0,w:100,h:100,color:'#f3eee7'},{type:'text',text:'ОСЕНЬ\nВ ГОРОДЕ',x:10,y:13,w:80,h:28,size:9,font:'Playfair Display',weight:700,color:'#1f3026'},{type:'text',text:'маленький гид по любимым местам',x:11,y:47,w:62,h:8,size:2.4,color:'#697168'}]},
  {name:'Фото и текст',icon:'▣',bg:'#ede5dc',els:[{type:'shape',shape:'rect',x:0,y:0,w:100,h:100,color:'#ede5dc'},{type:'text',text:'НАХОДИТЬ\nКРАСОТУ',x:10,y:13,w:54,h:21,size:7.2,font:'Space Grotesk',weight:700,color:'#2b2a26'},{type:'shape',shape:'rect',x:10,y:57,w:80,h:1,color:'#b98b65'},{type:'text',text:'в обычных вещах',x:10,y:64,w:55,h:6,size:2.6,color:'#655d55'}]},
  {name:'Полный кадр',icon:'◐',bg:'#1b2927',els:[{type:'shape',shape:'rect',x:0,y:0,w:100,h:100,color:'#1b2927'},{type:'text',text:'СОХРАНИ\nНА ВДОХНОВЕНИЕ',x:8,y:72,w:84,h:18,size:6.3,font:'Space Grotesk',weight:700,color:'#fff'},{type:'shape',shape:'circle',x:82,y:10,w:9,h:9,color:'#c7e2d2'}]}
];
function text(text,x,y,w,size,color='#1f3026',extra={}) { return {id:uid(),type:'text',text,x,y,w,h:size*1.5,size,font:'DM Sans',weight:500,color,opacity:1,align:'left',...extra}; }
function shape(shape,x,y,w,h,color) { return {id:uid(),type:'shape',shape,x,y,w,h,color,opacity:1,radius:0}; }
function demoSlides(){ return [
 {id:uid(),name:'Введение',bg:'#f2ede4',els:[shape('rect',0,0,100,100,'#f2ede4'),shape('circle',74,8,34,34,'#d7e7d6'),text('ТВОЯ\nОСЕНЬ',9,11,73,15,'#203a31',{font:'Playfair Display',weight:700,line:0.9}),text('5 идей для спокойных дней',10,47,58,3,'#64736a'),shape('line',10,62,25,0.5,'#cc8d62'),text('листай →',10,87,26,2.4,'#203a31',{weight:700})]},
 {id:uid(),name:'Слайд 2',bg:'#dfe7e2',els:[shape('rect',0,0,100,100,'#dfe7e2'),shape('rect',10,10,80,50,'#b2c4b8'),text('ЗАМЕДЛИСЬ',10,67,80,9,'#203a31',{font:'Space Grotesk',weight:700}),text('и выбери то, что наполняет',10,79,70,2.8,'#527064')]},
 {id:uid(),name:'Финал',bg:'#263934',els:[shape('rect',0,0,100,100,'#263934'),shape('circle',67,8,24,24,'#d0dfcc'),text('СОХРАНИ\nЭТОТ ПОСТ',10,42,80,11,'#fff',{font:'Playfair Display',weight:700,line:.9}),text('для следующей прогулки',10,72,60,2.8,'#d0dfcc')]}
]}
state.slides=demoSlides();
function ratio(){return state.format==='1:1'?1:1.25}
function activeSlide(){return state.slides[state.active]}
function snapshot(){state.history.push(JSON.stringify({slides:state.slides,active:state.active,format:state.format})); if(state.history.length>40)state.history.shift(); state.redo=[]}
function restore(next, target){ const now=JSON.stringify({slides:state.slides,active:state.active,format:state.format}); state[target].push(now); const d=JSON.parse(next); state.slides=d.slides;state.active=d.active;state.format=d.format;state.selected=null;render(); }
function undo(){if(state.history.length)restore(state.history.pop(),'redo')}; function redo(){if(state.redo.length)restore(state.redo.pop(),'history')}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function elementHTML(el){ let base=`data-id="${el.id}" class="element ${el.type} ${state.selected===el.id?'selected':''}" style="left:${el.x}%;top:${el.y}%;width:${el.w}%;height:${el.h}%;opacity:${el.opacity??1};z-index:${el.z||1}"`;
 if(el.type==='text') return `<div ${base} style="left:${el.x}%;top:${el.y}%;width:${el.w}%;height:${el.h}%;opacity:${el.opacity??1};z-index:${el.z||1};font-family:'${el.font}';font-size:${el.size}cqw;font-weight:${el.weight||400};color:${el.color};text-align:${el.align||'left'};line-height:${el.line||1.08};letter-spacing:${el.spacing||0}em;text-transform:${el.upper?'uppercase':'none'}">${esc(el.text).replace(/\n/g,'<br>')}</div>`;
 if(el.type==='image') return `<div ${base} class="element image ${state.selected===el.id?'selected':''}" style="left:${el.x}%;top:${el.y}%;width:${el.w}%;height:${el.h}%;opacity:${el.opacity??1};z-index:${el.z||1};border-radius:${el.radius||0}%"><img src="${el.src}" style="transform:scale(${el.scale||1}) translate(${el.ix||0}%,${el.iy||0}%);object-fit:${el.fit||'cover'}" /></div>`;
 return `<div ${base} class="element shape ${el.shape==='circle'?'circle':''} ${state.selected===el.id?'selected':''}" style="left:${el.x}%;top:${el.y}%;width:${el.w}%;height:${el.h}%;opacity:${el.opacity??1};z-index:${el.z||1};background:${el.shape==='line'?el.color:el.color};border-radius:${el.shape==='circle'?'50%':(el.radius||0)+'%'}"></div>`;
}
function canvas(){let s=activeSlide();return `<div id="canvas-wrap"><div id="canvas" style="--ratio:${ratio()};background:${s.bg}">${s.els.map(elementHTML).join('')}<div class="canvas-label">${state.format==='1:1'?'1080 × 1080':'1080 × 1350'}</div></div></div>`}
function slidesPanel(){return `<section class="side-section slides-section"><div class="section-title"><span>Слайды</span><button class="icon-btn" data-action="add-slide">＋</button></div><div class="slide-list">${state.slides.map((s,i)=>`<button class="slide-item ${i===state.active?'active':''}" data-slide="${i}" draggable="true"><span class="slide-number">${String(i+1).padStart(2,'0')}</span><span class="slide-mini" style="background:${s.bg}"><i style="background:${s.els.find(e=>e.type==='text')?.color||'#fff'}"></i></span><span>${esc(s.name)}</span><b>⋮⋮</b></button>`).join('')}</div><button class="wide-button muted" data-action="add-slide">＋ Добавить слайд</button></section>`}
function side(){let contents={slides:slidesPanel(),templates:`<section class="side-section"><div class="section-title">Шаблоны</div><p class="hint">Начните с готовой композиции</p><div class="templates">${templates.map((t,i)=>`<button class="template" data-template="${i}"><span>${t.icon}</span><b>${t.name}</b></button>`).join('')}</div></section>`,uploads:`<section class="side-section"><div class="section-title">Загрузки</div><button class="upload-zone" data-action="upload">↑<strong>Загрузить фото</strong><small>PNG, JPG или WEBP</small></button><p class="hint">Выберите файл — он сразу появится на слайде.</p></section>`,text:`<section class="side-section"><div class="section-title">Текст</div><button class="add-text" data-action="text" style="font-family:'DM Sans'">Добавить заголовок</button><button class="add-text" data-action="text-small">Добавить основной текст</button></section>`,shapes:`<section class="side-section"><div class="section-title">Фигуры</div><div class="shapes-grid"><button data-action="shape-rect">□<small>Прямоугольник</small></button><button data-action="shape-circle">○<small>Круг</small></button><button data-action="shape-line">—<small>Линия</small></button></div></section>`,styles:`<section class="side-section"><div class="section-title">Стили</div><p class="hint">Применяются к текущему слайду</p><div class="style-presets">${[['Minimal','#f2ede4','#203a31'],['Dark','#263934','#ffffff'],['Soft','#f2d8d7','#542e3b'],['Bold','#ff5c39','#1c1820']].map((x,i)=>`<button data-style="${i}" style="--pbg:${x[1]};--pfg:${x[2]}"><i></i><span>${x[0]}</span></button>`).join('')}</div></section>`};return `<aside class="left"><nav>${[['slides','▱','Слайды'],['templates','▦','Шаблоны'],['uploads','↑','Загрузки'],['text','T','Текст'],['shapes','○','Фигуры'],['styles','✦','Стили']].map(x=>`<button data-tool="${x[0]}" class="${state.tool===x[0]?'on':''}"><i>${x[1]}</i><span>${x[2]}</span></button>`).join('')}</nav><div class="side-content">${contents[state.tool]}</div></aside>`}
function prop(){let el=activeSlide().els.find(x=>x.id===state.selected); if(!el)return `<aside class="right empty"><div class="empty-mark">✦</div><h3>Выберите элемент</h3><p>Кликните по тексту, фото или фигуре на макете, чтобы настроить его.</p></aside>`;let common=`<div class="prop-grid"><label>X<input data-prop="x" type="number" value="${Math.round(el.x)}"></label><label>Y<input data-prop="y" type="number" value="${Math.round(el.y)}"></label><label>Ширина<input data-prop="w" type="number" value="${Math.round(el.w)}"></label><label>Высота<input data-prop="h" type="number" value="${Math.round(el.h)}"></label></div>`; let specific=el.type==='text'?`<label>Текст<textarea data-prop="text">${esc(el.text)}</textarea></label><div class="prop-grid"><label>Шрифт<select data-prop="font">${['DM Sans','Space Grotesk','Playfair Display'].map(x=>`<option ${x===el.font?'selected':''}>${x}</option>`).join('')}</select></label><label>Размер<input data-prop="size" type="number" step=".2" value="${el.size}"></label></div><div class="prop-grid"><label>Цвет<input data-prop="color" type="color" value="${el.color}"></label><label>Начертание<select data-prop="weight"><option value="400">Обычное</option><option value="700" ${el.weight>=700?'selected':''}>Жирное</option></select></label></div>`: el.type==='image'?`<div class="property-row"><button data-action="fit">Fit</button><button data-action="fill">Fill</button><button data-action="reset-image">Сбросить</button></div><div class="prop-grid"><label>Масштаб<input data-prop="scale" type="number" step=".1" value="${el.scale||1}"></label><label>Скругление<input data-prop="radius" type="number" value="${el.radius||0}"></label></div>`:`<div class="prop-grid"><label>Цвет<input data-prop="color" type="color" value="${el.color}"></label><label>Скругление<input data-prop="radius" type="number" value="${el.radius||0}"></label></div>`;return `<aside class="right"><div class="right-head"><h3>${el.type==='text'?'Текст':el.type==='image'?'Фото':'Фигура'}</h3><button class="icon-btn" data-action="delete">⌫</button></div>${specific}<hr><h4>Позиция и размер</h4>${common}<label>Прозрачность <input data-prop="opacity" type="range" min="0" max="1" step=".05" value="${el.opacity??1}"></label><div class="align-row"><button data-align="left">⇤</button><button data-align="center">↔</button><button data-align="right">⇥</button><button data-align="top">⇡</button><button data-align="middle">↕</button><button data-align="bottom">⇣</button></div><hr><h4>Слой</h4><div class="property-row"><button data-action="back">Назад</button><button data-action="front">Вперёд</button><button data-action="duplicate">Дублировать</button></div>${el.type==='image'?`<button class="wide-button split" data-action="split">✦ Разделить на слайды</button>`:''}</aside>`}
function render(){ $('#app').innerHTML=`<header class="top"><a class="brand">slide<span>ful</span></a><div class="project"><input id="project-name" value="${esc(state.projectName)}"><small>Сохранено локально</small></div><div class="top-actions"><button data-action="undo" title="Undo">↶</button><button data-action="redo" title="Redo">↷</button><span></span><button data-action="preview">▷ Предпросмотр</button><button class="export" data-action="export">Экспортировать ↗</button></div></header><main>${side()}<section class="workspace"><div class="format-bar"><span>Instagram carousel</span><div><button data-format="1:1" class="${state.format==='1:1'?'active':''}">1:1</button><button data-format="4:5" class="${state.format==='4:5'?'active':''}">4:5</button></div></div>${canvas()}</section>${prop()}</main><footer><div class="slides-footer">${state.slides.map((s,i)=>`<button data-slide="${i}" class="thumb ${i===state.active?'active':''}"><span style="background:${s.bg}">${i+1}</span><small>${i===state.active?'Текущий':'Слайд '+(i+1)}</small></button>`).join('')}<button class="new-thumb" data-action="add-slide">＋</button></div><div class="tips">⌘/Ctrl + Z отменить &nbsp; · &nbsp; Delete удалить &nbsp; · &nbsp; ⌘/Ctrl + D дублировать</div></footer>`;bind()}
function bind(){document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;render()});document.querySelectorAll('[data-slide]').forEach(b=>b.onclick=()=>{state.active=+b.dataset.slide;state.selected=null;render()});document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>{snapshot();state.format=b.dataset.format;render()});document.querySelectorAll('[data-template]').forEach(b=>{snapshot();let t=templates[+b.dataset.template];activeSlide().bg=t.bg;activeSlide().els=deep(t.els).map(e=>({...e,id:uid()}));render()});document.querySelectorAll('[data-style]').forEach(b=>b.onclick=()=>{let x=[['#f2ede4','#203a31'],['#263934','#fff'],['#f2d8d7','#542e3b'],['#ff5c39','#1c1820']][+b.dataset.style];snapshot();let s=activeSlide();s.bg=x[0];s.els.forEach(e=>{if(e.type==='shape'&&e.x===0&&e.y===0)e.color=x[0];if(e.type==='text')e.color=x[1]});render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));document.querySelectorAll('[data-prop]').forEach(i=>i.oninput=()=>{let e=current();if(!e)return;snapshot();let v=i.type==='number'||i.type==='range'?+i.value:i.value;e[i.dataset.prop]=v;render()});document.querySelectorAll('[data-align]').forEach(b=>b.onclick=()=>align(b.dataset.align));$('#project-name').onchange=e=>{state.projectName=e.target.value;save()};$('#canvas').addEventListener('pointerdown',startDrag);document.querySelectorAll('.slide-item').forEach(item=>{item.ondragstart=()=>state.dragging=+item.dataset.slide;item.ondragover=e=>e.preventDefault();item.ondrop=e=>{e.preventDefault();let from=state.dragging,to=+item.dataset.slide;if(from!==to){snapshot();let [s]=state.slides.splice(from,1);state.slides.splice(to,0,s);state.active=to;render()}}})}
function current(){return activeSlide().els.find(e=>e.id===state.selected)}
function startDrag(ev){let target=ev.target.closest('.element');if(!target){state.selected=null;render();return}ev.stopPropagation();let e=activeSlide().els.find(x=>x.id===target.dataset.id);state.selected=e.id;render();let c=$('#canvas').getBoundingClientRect(),sx=ev.clientX,sy=ev.clientY,ox=e.x,oy=e.y; snapshot();function move(v){e.x=Math.max(0,Math.min(100-e.w,ox+(v.clientX-sx)/c.width*100));e.y=Math.max(0,Math.min(100-e.h,oy+(v.clientY-sy)/c.height*100));let dom=document.querySelector(`[data-id="${e.id}"]`);if(dom){dom.style.left=e.x+'%';dom.style.top=e.y+'%'}}function up(){window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);render()}window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function action(a){let s=activeSlide(),e=current();if(a==='add-slide'){snapshot();state.slides.splice(state.active+1,0,{id:uid(),name:'Новый слайд',bg:'#f7f5f1',els:[shape('rect',0,0,100,100,'#f7f5f1')]});state.active++;render()}if(a==='text'||a==='text-small'){snapshot();let n=a==='text'?text('НОВЫЙ\nЗАГОЛОВОК',10,18,80,10,'#203a31',{font:'Space Grotesk',weight:700}):text('Введите текст',10,55,70,3,'#203a31');s.els.push(n);state.selected=n.id;render()}if(a.startsWith('shape-')){snapshot();let kind=a.replace('shape-','');let n=shape(kind,20,20,kind==='line'?55:40,kind==='line'?1:25,'#203a31');s.els.push(n);state.selected=n.id;render()}if(a==='upload')$('#file-input').click();if(a==='delete'&&e){snapshot();s.els=s.els.filter(x=>x.id!==e.id);state.selected=null;render()}if(a==='duplicate'&&e){snapshot();let n=deep(e);n.id=uid();n.x=Math.min(100-n.w,e.x+3);n.y=Math.min(100-n.h,e.y+3);s.els.push(n);state.selected=n.id;render()}if(a==='undo')undo();if(a==='redo')redo();if(a==='preview')preview();if(a==='export')exportAll();if(a==='fit'&&e){snapshot();e.fit='contain';e.scale=1;render()}if(a==='fill'&&e){snapshot();e.fit='cover';e.scale=1;render()}if(a==='reset-image'&&e){snapshot();Object.assign(e,{scale:1,ix:0,iy:0,fit:'cover'});render()}if(a==='front'&&e){snapshot();e.z=Math.max(...s.els.map(x=>x.z||1))+1;render()}if(a==='back'&&e){snapshot();e.z=Math.min(...s.els.map(x=>x.z||1))-1;render()}if(a==='split'&&e)splitImage(e)}
function align(a){let e=current();if(!e)return;snapshot();if(a==='left')e.x=0;if(a==='center')e.x=(100-e.w)/2;if(a==='right')e.x=100-e.w;if(a==='top')e.y=0;if(a==='middle')e.y=(100-e.h)/2;if(a==='bottom')e.y=100-e.h;render()}
$('#file-input').onchange=ev=>{[...ev.target.files].forEach(f=>{let r=new FileReader;r.onload=()=>{snapshot();let e={id:uid(),type:'image',src:r.result,x:10,y:15,w:80,h:55,opacity:1,scale:1,fit:'cover',radius:0};activeSlide().els.push(e);state.selected=e.id;render()};r.readAsDataURL(f)});ev.target.value=''};
function splitImage(e){let n=+prompt('На сколько слайдов разделить изображение? (2–4)', '2');if(!n||n<2||n>4)return;snapshot();let at=state.active; let source=deep(e);activeSlide().els=activeSlide().els.filter(x=>x.id!==e.id);for(let i=0;i<n;i++){let sl=i===0?activeSlide():{id:uid(),name:'Часть '+(i+1),bg:activeSlide().bg,els:[shape('rect',0,0,100,100,activeSlide().bg)]};let part={...source,id:uid(),x:0,y:0,w:100,h:100,split:{index:i,total:n}};sl.els.push(part);if(i>0)state.slides.splice(at+i,0,sl)}state.selected=null;render()}
function preview(){let m=document.createElement('div');m.className='modal';let i=state.active;function paint(){let s=state.slides[i];m.innerHTML=`<div class="preview"><button class="close">×</button><p>Предпросмотр карусели <small>${i+1} / ${state.slides.length}</small></p><div class="preview-canvas" style="--ratio:${ratio()};background:${s.bg}">${s.els.map(elementHTML).join('')}</div><div class="preview-controls"><button class="prev" ${i===0?'disabled':''}>←</button><span>${state.slides.map((_,x)=>`<i class="${x===i?'on':''}"></i>`).join('')}</span><button class="next" ${i===state.slides.length-1?'disabled':''}>→</button></div></div>`;$('.close',m).onclick=()=>m.remove();$('.prev',m).onclick=()=>{i--;paint()};$('.next',m).onclick=()=>{i++;paint()}}paint();document.body.append(m)}
async function exportAll(){let c=document.createElement('canvas'),ctx=c.getContext('2d'),w=1080,h=state.format==='1:1'?1080:1350;c.width=w;c.height=h;let s=activeSlide();ctx.fillStyle=s.bg;ctx.fillRect(0,0,w,h);for(const e of s.els){ctx.globalAlpha=e.opacity??1;if(e.type==='shape'){ctx.fillStyle=e.color;if(e.shape==='circle'){ctx.beginPath();ctx.ellipse((e.x+e.w/2)*w/100,(e.y+e.h/2)*h/100,e.w*w/200,e.h*h/200,0,0,Math.PI*2);ctx.fill()}else ctx.fillRect(e.x*w/100,e.y*h/100,e.w*w/100,e.h*h/100)}if(e.type==='image'){let img=new Image();await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=e.src});let x=e.x*w/100,y=e.y*h/100,iw=e.w*w/100,ih=e.h*h/100;ctx.save();ctx.beginPath();ctx.rect(x,y,iw,ih);ctx.clip();let scale=e.fit==='contain'?Math.min(iw/img.width,ih/img.height):Math.max(iw/img.width,ih/img.height);let dw=img.width*scale*(e.scale||1),dh=img.height*scale*(e.scale||1);ctx.drawImage(img,x+(iw-dw)/2,y+(ih-dh)/2,dw,dh);ctx.restore()}if(e.type==='text'){ctx.fillStyle=e.color;ctx.font=`${e.weight||400} ${e.size*w/100}px ${e.font}`;ctx.textAlign=e.align||'left';e.text.split('\n').forEach((line,i)=>ctx.fillText(line,e.x*w/100,(e.y+e.size*(i+1)*1.05)*h/100))}}ctx.globalAlpha=1;let a=document.createElement('a');a.download=`${String(state.active+1).padStart(2,'0')}-${state.projectName}.png`;a.href=c.toDataURL('image/png');a.click()}
function save(){localStorage.setItem('slideful-project',JSON.stringify({slides:state.slides,format:state.format,projectName:state.projectName}))};window.addEventListener('beforeunload',save);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key==='d'){e.preventDefault();action('duplicate')}if(e.key==='Delete')action('delete');let n=current();if(n&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();snapshot();let d=e.shiftKey?5:1;if(e.key==='ArrowLeft')n.x-=d;if(e.key==='ArrowRight')n.x+=d;if(e.key==='ArrowUp')n.y-=d;if(e.key==='ArrowDown')n.y+=d;render()}});render();
